apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  selector:
    matchLabels:
      app: adminer
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: adminer
        tier: frontend
    spec:
      containers:
      - image: adminer
        name: adminer
        ports:
        - containerPort: 80
          name: adminer
        resources:
          limits:
            cpu: 50m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 10Mi
---

# Lastly we need service (and ingress)
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  ports:
    - port: 80
  selector:
    app: adminer
    tier: frontend
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: adminer
spec:
  rules:
  - host: adminer.demo.wbitt.com
    http:
      paths:
      - path: /
        backend:
          serviceName: adminer
          servicePort: http

